CREATE TABLE IF NOT EXISTS genero (
    id_genero INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50)
);



CREATE TABLE IF NOT EXISTS filme (
    id_filme INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100)  NOT NULL UNIQUE,
    descricao VARCHAR(150) NOT NULL,
    diretor VARCHAR(60) NOT NULL,
    url VARCHAR(250) NOT NULL,
    fk_genero INT NOT NULL,
    FOREIGN KEY (fk_genero) REFERENCES genero(id_genero)

);

INSERT INTO genero (nome) VALUES ('Ação');
INSERT INTO genero (nome) VALUES ('Comédia');
INSERT INTO genero (nome) VALUES ('Terror');
INSERT INTO genero (nome) VALUES ('Drama');
INSERT INTO genero (nome) VALUES ('Ficção Científica');
INSERT INTO genero (nome) VALUES ('Romance');
INSERT INTO genero (nome) VALUES ('Suspense');
INSERT INTO genero (nome) VALUES ('Animação');
INSERT INTO genero (nome) VALUES ('Documentário');
INSERT INTO genero (nome) VALUES ('Aventura');
INSERT INTO genero (nome) VALUES ('Fantasia');

INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('Duro de Matar', 'Um policial nova-iorquino enfrenta terroristas em um arranha-céu de Los Angeles.', 'John McTiernan', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWBop024mKDaxixTIfdayRjxyqobNUV5v4w4CuXgro0A&s=10', 1);
INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('Mad Max: Estrada da Fúria', 'Em um deserto pós-apocalíptico, Max se junta a Furiosa para escapar de um tirano.', 'George Miller', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3Te-rIpOlbjxGDO0h3kNH0AOIUQX0lDDLdNDWLAHGjA&s=10', 1);
INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('Se Beber, Não Case!', 'Três amigos acordam sem lembrar da noite anterior e sem o noivo, que sumiu antes do casamento.', 'Todd Phillips', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9kfvLk76M7X94mx9jTTHdMNcGeUBmIdun5n_0BJYL0g&s=10', 2);
INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('Superbad', 'Dois amigos adolescentes tentam comprar bebida para uma festa antes de se separarem para a faculdade.', 'Greg Mottola', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTa7q4LlQctL9sULwuuk96JZW2q3vfPDv877F6EWjFDdQ&s=10', 2);
INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('O Iluminado', 'Um escritor se torna zelador de um hotel isolado e mergulha na loucura durante o inverno.', 'Stanley Kubrick', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAg3UtJTJrIRSJUUW4qhRDUvz2Rkc-nmZrISYXp-hMDA&s=10', 3);