CREATE TABLE IF NOT EXISTS genero (
    id_genero INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50)
);



CREATE TABLE IF NOT EXISTS filme (
    id_filme INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100)  NOT NULL UNIQUE,
    descricao VARCHAR(150) NOT NULL,
    diretor VARCHAR(60) NOT NULL,
    url VARCHAR(250) NOT NULL,
    fk_genero INT NOT NULL,
    FOREIGN KEY (fk_genero) REFERENCES genero(id_genero)

);

INSERT INTO genero (nome) VALUES ('Ação');
INSERT INTO genero (nome) VALUES ('Comédia');
INSERT INTO genero (nome) VALUES ('Terror');
INSERT INTO genero (nome) VALUES ('Drama');
INSERT INTO genero (nome) VALUES ('Ficção Científica');
INSERT INTO genero (nome) VALUES ('Romance');
INSERT INTO genero (nome) VALUES ('Suspense');
INSERT INTO genero (nome) VALUES ('Animação');
INSERT INTO genero (nome) VALUES ('Documentário');
INSERT INTO genero (nome) VALUES ('Aventura');
INSERT INTO genero (nome) VALUES ('Fantasia');

INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('Duro de Matar', 'Um policial nova-iorquino enfrenta terroristas em um arranha-céu de Los Angeles.', 'John McTiernan', 'https://example.com/duro-de-matar.jpg', 1);
INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('Mad Max: Estrada da Fúria', 'Em um deserto pós-apocalíptico, Max se junta a Furiosa para escapar de um tirano.', 'George Miller', 'https://example.com/mad-max.jpg', 1);
INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('Se Beber, Não Case!', 'Três amigos acordam sem lembrar da noite anterior e sem o noivo, que sumiu antes do casamento.', 'Todd Phillips', 'https://example.com/se-beber-nao-case.jpg', 2);
INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('Superbad', 'Dois amigos adolescentes tentam comprar bebida para uma festa antes de se separarem para a faculdade.', 'Greg Mottola', 'https://example.com/superbad.jpg', 2);
INSERT INTO filme (titulo, descricao, diretor, url, fk_genero) VALUES ('O Iluminado', 'Um escritor se torna zelador de um hotel isolado e mergulha na loucura durante o inverno.', 'Stanley Kubrick', 'https://example.com/o-iluminado.jpg', 3);