CREATE TABLE IF NOT EXISTS genero (
    id_genero INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50)
);



CREATE TABLE IF NOT EXISTS filme (
    id_filme INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(100)  NOT NULL UNIQUE,
    fk_genero INT NOT NULL,
    FOREIGN KEY (fk_genero) REFERENCES genero(id_genero)

);

INSERT INTO genero (nome) VALUES ('Ação');
INSERT INTO genero (nome) VALUES ('Comédia');
INSERT INTO genero (nome) VALUES ('Terror');
INSERT INTO genero (nome) VALUES ('Drama');
INSERT INTO genero (nome) VALUES ('Ficção Científica');
INSERT INTO genero (nome) VALUES ('Romance');
INSERT INTO genero (nome) VALUES ('Suspense');
INSERT INTO genero (nome) VALUES ('Animação');
INSERT INTO genero (nome) VALUES ('Documentário');
INSERT INTO genero (nome) VALUES ('Aventura');
INSERT INTO genero (nome) VALUES ('Fantasia');

INSERT INTO filme (titulo, fk_genero) VALUES ('Duro de Matar', 1);
INSERT INTO filme (titulo, fk_genero) VALUES ('Mad Max: Estrada da Fúria', 1);
INSERT INTO filme (titulo, fk_genero) VALUES ('Se Beber, Não Case!', 2);
INSERT INTO filme (titulo, fk_genero) VALUES ('Superbad', 2);
INSERT INTO filme (titulo, fk_genero) VALUES ('O Iluminado', 3);